#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aafp.Cme.Api.Templates
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 6 "C:\svn\Aafp Apis\Cme\trunk\src\Cme.Api\Templates\CmeStatsUnauthenticatedTemplate.cshtml"
    using Aafp.Cme.Api;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class CmeStatsUnauthenticatedTemplate : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        #line 8 "C:\svn\Aafp Apis\Cme\trunk\src\Cme.Api\Templates\CmeStatsUnauthenticatedTemplate.cshtml"

    public dynamic Model { get; set; }

        #line default
        #line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n");


WriteLiteral("\r\n");


WriteLiteral("\r\n\r\n<div id=\"cmeNumericStatsDiv\">\r\n    <div class=\"mini-dashboard\">\r\n        <h1 " +
"class=\"mini-dashboard__title mini-dashboard--hidable\"><a href=\"");


            
            #line 14 "C:\svn\Aafp Apis\Cme\trunk\src\Cme.Api\Templates\CmeStatsUnauthenticatedTemplate.cshtml"
                                                                       Write($"{ApplicationConfig.BaseUrl}/my-cme/");

            
            #line default
            #line hidden
WriteLiteral(@""">My Quizzes and Courses</a></h1>
        <div class=""mini-dashboard__wrapper"">
            <div class=""mini-dashboard__data dashboard-numeric mini-dashboard--hidable"">
                <span class=""dashboard-numeric__numeral"">40+</span>
                <span class=""dashboard-numeric__units"">credits of</span>
                <a id=""js-stats-subscriptions"" href=""");


            
            #line 19 "C:\svn\Aafp Apis\Cme\trunk\src\Cme.Api\Templates\CmeStatsUnauthenticatedTemplate.cshtml"
                                                 Write($"{ApplicationConfig.BaseUrl}/my-cme/");

            
            #line default
            #line hidden
WriteLiteral("\" class=\"dashboard-numeric__desc\">quizzes available</a>\r\n            </div>\r\n    " +
"        <div class=\"mini-dashboard__data dashboard-alpha\">\r\n                <p c" +
"lass=\"dashboard-numeric__desc\"><a href=\"");


            
            #line 22 "C:\svn\Aafp Apis\Cme\trunk\src\Cme.Api\Templates\CmeStatsUnauthenticatedTemplate.cshtml"
                                                        Write($"{ApplicationConfig.BaseUrl}/my-cme/");

            
            #line default
            #line hidden
WriteLiteral(@""">Sign in to view more</a></p>
            </div>
        </div>
    </div>
</div>
<div id=""reElectionStatusDiv"">
    <div class=""mini-dashboard mini-dashboard--mobile-hide"">
        <h1 class=""mini-dashboard__title"">Membership</h1>
        <div class=""mini-dashboard__wrapper"">
            <div class=""mini-dashboard__data dashboard-alpha"">
                <span>Re-Election status</span>
                <p><a href=""");


            
            #line 33 "C:\svn\Aafp Apis\Cme\trunk\src\Cme.Api\Templates\CmeStatsUnauthenticatedTemplate.cshtml"
                        Write($"{ApplicationConfig.BaseUrl}/cme/reporting");

            
            #line default
            #line hidden
WriteLiteral("\">Sign in to view</a></p>\r\n            </div>\r\n            <div class=\"mini-dashb" +
"oard__data dashboard-alpha\">\r\n                <a href=\"");


            
            #line 36 "C:\svn\Aafp Apis\Cme\trunk\src\Cme.Api\Templates\CmeStatsUnauthenticatedTemplate.cshtml"
                     Write($"{ApplicationConfig.BaseUrl}/cme/reporting/claimcredit.aspx");

            
            #line default
            #line hidden
WriteLiteral("\" class=\"dashboard-alpha__button button button-secondary\" id=\"js-report-cme\">Repo" +
"rt CME</a>\r\n                <a href=\"");


            
            #line 37 "C:\svn\Aafp Apis\Cme\trunk\src\Cme.Api\Templates\CmeStatsUnauthenticatedTemplate.cshtml"
                     Write($"{ApplicationConfig.BaseUrl}/cme/reporting/transcript.aspx");

            
            #line default
            #line hidden
WriteLiteral(@""" class=""dashboard-alpha__button button button-secondary"" id=""js-view-transcript"">View Transcript</a>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {

        $(""#js-stats-subscriptions"").click(function () {
            clickCMEEvent(""my cme - quizzes available"");
        });

        $(""#js-report-cme"").click(function () {
            clickCMEEvent(""my cme – report CME"");
        });

        $(""#js-view-transcript"").click(function () {
            clickCMEEvent(""my cme – view transcript"");
        });

        $(""#js-report-cme, #js-view-transcript"").dblclick(function (event) {
            event.preventDefault();
        });
    });

    function clickCMEEvent(title) {
        try {
            if (title && """" != title) {
                var s = s_gi(s_account);
                s.eVar26 = title;
                s.events = 'event26';
                //Track eVar & Event
                s.linkTrackVars = ""events,eVar26""
                s.linkTrackEvents = ""event26""
                s.tl(this, 'o', s.pageName + "":"" + s.eVar26);
            }
        } catch (e) {
            //console.log(""Error setting SC: "" + e);
        }
    }
</script>");


        }
    }
}
#pragma warning restore 1591
